
module.exports = {
    SUCCESS : 1,
    USER_ALREADY_EXIST : 2,
    FAILURE : 3,
    INVALID_USERNAME_PASSWORD : 4,
    INVALID_PARAMETERS : 5,
    RECORD_FOUND : 6,
    RECORD_NOT_FOUND : 7,
    RECORD_CREATED: 8,
    RECORD_NOT_CREATED : 9,
    INVALID_AUTH_TOKEN : 10,
    INVALID_REF_TOKEN: 11
};