
module.exports = {
    SUCCESS : 1,
    FAILURE : 2,
    INVALID_USERNAME_PASSWORD : 3,
    INVALID_PARAMETERS : 4,
    RECORD_FOUND : 5,
    RECORD_NOT_FOUND : 6,
    RECORD_CREATED: 7,
    RECORD_UPDATED: 8,
    RECORD_NOT_CREATED : 9,
    INVALID_AUTH_TOKEN : 10,
    INVALID_REF_TOKEN: 11,
    RECORD_ALREADY_EXISTS : 12,
    RECORD_MODIFIED: 13,
    REQUEST_SENT: 14,
    AUTHORIZATION_ERROR: 15 
};